export const BRAND_NAME = 'SayVid';
export const TRANSCRIPT_FAIL_ERROR_MESSAGE =
  'there were some errors in getting transcript, try again later.';
export const NOT_A_YOUTUBE_VIDEO_ERROR_MESSAGE = 'not a youtube video url.';
export const TRANSCRIPT_NOT_FOUND_ERROR_MESSAGE = 'transcript not found.';
export const INITIAL_PROMPT_WITH_FOLLOWING_TRANSCRIPT = `as a professional blog writer, after reading the below written transcript, create and reply with only a blog. Append "Generated by ${BRAND_NAME}" at the end of blog.`;
export const CANNOT_GET_VIDEO_INFO = 'cannot get video info';
export const INFO_FAIL_ERROR_MESSAGE =
  'there were some errors in getting video info, try again later.';
